---
# This role contains common plays that will run on all nodes.

- name: include vars
  include_vars: "group_vars/switch_list"

- name: Get Date
  action: shell date +"%Y-%m-%d" 
  register: today
  ignore_errors: yes

- name: add host record jc
  #debug: msg="{{ item }}"
  script: sw.log.redirect.to.tftp {{ item.key }} {{ item.value.name}} {{ item.value.passwd }} {{ item.value.enable }} {{ today.stdout }}
  with_dict: "{{ jc_sw_info }}"
  ignore_errors: yes

- name: add host record nj
  #debug: msg="{{ item }}"
  script: sw.log.redirect.to.tftp {{ item.key }} {{ item.value.name}} {{ item.value.passwd }} {{ item.value.enable }} {{ today.stdout }}
  with_dict: "{{ nj_sw_info }}"
  ignore_errors: yes
