---
# This playbook perform a restart task

- name: fetch files
  hosts: jc-lvs nj-lvs dl-lvs
  remote_user: root
  roles:
    - conf-fetch-lvs-server

- name: intall rsync rpm
  hosts: jc-lvs nj-lvs dl-lvs
  remote_user: root
  roles:
    - common

- name: sync directories
  hosts: jc-lvs nj-lvs dl-lvs
  remote_user: root
  roles:
    - dir-sync-lvs-server
