---
# This playbook perform a restart task

- name: fetch files
  hosts: jc-dns nj-dns
  remote_user: root
  roles:
    - conf-fetch-dns-server

- name: intall rsync rpm
  hosts: jc-dns nj-dns
  remote_user: root
  roles:
    - common

- name: sync directories
  hosts: jc-dns nj-dns
  remote_user: root
  roles:
    - dir-sync-dns-server
