---
# This role contains common plays that will run on all nodes.

- name: scp mail.sh to remote host
  copy: src=../files/mail.sh dest=/tmp/mail.sh owner=root group=root mode="u=rwx,g=r,o=r"

- name: execute mail.sh
  shell: sh /tmp/mail.sh

- name: send a test mail
  shell: date | mailx -s "test" yfding@mail.etonenet.com

- name: delete mail.sh
  file: path='/tmp/mail.sh' state=absent
