---
# This role contains common plays that will run on all nodes.

- name: include vars
  include_vars: "group_vars/boss3_log_list"

- name: Get Date
  action: shell date -d "-1 day" +"%Y-%m-%d" 
  register: yestoday


- name: Get Directory list
  shell: cd /var/opt/httpdlogs; (find . -maxdepth 1 -type d | cut -d'/' -f2)
  register: dirlist

- name: Fetch remote file to ansible path tmp
  #shell: echo "{{ groups['jc_apache'] }}"
  fetch: src=/var/opt/httpdlogs/{{ item }}/access_log.{{ yestoday.stdout }} dest=/tmp/tmp/
  with_items: "{{dirlist.stdout_lines}}"
  when: "'{{ ansible_host }}' in groups['jc_apache']"
  ignore_errors: yes
  tags:
    - task-fetch-files

- name: Fetch remote file to ansible path tmp
  #shell: echo "{{ groups['nj_apache'] }}"
  fetch: src=/var/opt/httpdlogs/{{ item }}/access_log.{{ yestoday.stdout }} dest=/tmp/tmp/
  with_items: "{{dirlist.stdout_lines}}"
  when: "'{{ ansible_host }}' in groups['nj_apache']"
  ignore_errors: yes
  tags:
    - task-fetch-files

